const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const srcDataDir = path.join(rootDir, 'src', 'data');
const outputFile = path.join(srcDataDir, 'products.ts');

const foldersToScan = [
  '1. Horeca Seating',
  '2. Horeca Tables',
  '4. Outdoor Furniture',
  '5. Other Products'
];

const bgColors = ['#eef1ed', '#f3f3f3', '#f4f0eb', '#f4eff1'];
const defaultColors = ['#000000', '#ffffff', '#78350f', '#c49a6c'];

let products = [];
let imgImports = [];
let idCounter = 1;

function findProducts(dir, currentCategory) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    
    if (entry.isDirectory()) {
      findProducts(fullPath, currentCategory);
    } else if (entry.isFile() && (entry.name === 'product.md' || entry.name === 'product_intelligence.md')) {
      processProductFolder(dir, currentCategory);
      // Once we process a folder for a product, break out of processing other md files in this specific directory to avoid duplicates
      break; 
    }
  }
}

function processProductFolder(dir, mainCategory) {
  const mdFiles = ['product.md', 'product_intelligence.md'];
  let mdContent = '';
  
  for (const file of mdFiles) {
    const p = path.join(dir, file);
    if (fs.existsSync(p)) {
      mdContent += fs.readFileSync(p, 'utf-8') + '\n';
    }
  }

  // Extract Name
  let name = 'Unknown Product';
  const nameMatch = mdContent.match(/(?:Product Name|Product Title):\s*(.*)/i);
  if (nameMatch && nameMatch[1]) {
    name = nameMatch[1].trim();
  }

  // Extract Code/ID
  let code = 'UNKNOWN-000';
  const codeMatch = mdContent.match(/(?:Product ID|Product Code|SKU):\s*(.*)/i);
  if (codeMatch && codeMatch[1]) {
    code = codeMatch[1].trim();
  }

  // Get Subcategory from folder structure. Usually it's the folder under the main folder.
  // e.g., rootDir/1. Horeca Seating/Indoor Chairs/New Folder -> "Indoor Chairs"
  const relativeToRoot = path.relative(rootDir, dir);
  const parts = relativeToRoot.split(path.sep);
  let subCategory = mainCategory;
  if (parts.length > 1) {
    subCategory = parts[1];
  }

  // Find image
  const entries = fs.readdirSync(dir);
  const imgFile = entries.find(f => f.endsWith('.webp') || f.endsWith('.jpg') || f.endsWith('.png'));
  
  if (imgFile) {
    const imgVar = `img${idCounter}`;
    
    // Calculate import path.
    // products.ts is in src/data. Root is ../../ from src/data
    // relativeToRoot is e.g. "1. Horeca Seating/Indoor Chairs/New folder"
    let importPath = `../../${relativeToRoot.replace(/\\/g, '/')}/${imgFile}`;
    
    // Escape single quotes if necessary, though paths shouldn't really have them
    importPath = importPath.replace(/'/g, "\\'");

    imgImports.push(`import ${imgVar} from '${importPath}';`);
    
    products.push({
      id: idCounter,
      name: name,
      code: code,
      category: subCategory,
      imageVar: imgVar,
      bgColor: bgColors[idCounter % bgColors.length],
      price: 89 + (idCounter * 7) % 150 // Generate a pseudo-random price between $89 and $238
    });
    
    idCounter++;
  } else {
      console.warn('No image found for product in', dir);
  }
}

console.log('Starting scan...');
for (const folder of foldersToScan) {
  const folderPath = path.join(rootDir, folder);
  if (fs.existsSync(folderPath)) {
    findProducts(folderPath, folder.replace(/^\d+\.\s*/, '')); // Remove '1. ' prefix for category
  }
}

if (!fs.existsSync(srcDataDir)) {
  fs.mkdirSync(srcDataDir, { recursive: true });
}

let tsContent = `// Automatically generated by scripts/generateProducts.js
${imgImports.join('\n')}

export interface Product {
  id: number;
  name: string;
  code: string;
  category: string;
  image: string;
  colors: string[];
  bgColor: string;
  price: number;
}

export const allProducts: Product[] = [
${products.map(p => `  {
    id: ${p.id},
    name: "${p.name.replace(/"/g, '\\"')}",
    code: "${p.code}",
    category: "${p.category}",
    image: ${p.imageVar},
    colors: ['#000000', '#ffffff', '#78350f', '#c49a6c'],
    bgColor: "${p.bgColor}",
    price: ${p.price}
  }`).join(',\n')}
];

export const categoryList = [
  ...new Set(allProducts.map(p => p.category))
].map(catName => ({
  name: catName,
  count: allProducts.filter(p => p.category === catName).length
}));

export const colorList = [
  { name: 'Black', count: 42, hex: 'bg-[#000000]' },
  { name: 'White', count: 28, hex: 'bg-[#ffffff]' },
  { name: 'Brown', count: 35, hex: 'bg-amber-800' },
  { name: 'Beige', count: 16, hex: 'bg-[#e8e2d2]' },
  { name: 'Grey', count: 22, hex: 'bg-gray-400' }
];
`;

fs.writeFileSync(outputFile, tsContent);
console.log(`Generated ${outputFile} with ${products.length} products.`);
