// Automatically generated by scripts/generateProducts.js
import img1_1 from '../../1. Horeca Seating/Bar Chairs/RFBC0101/ZEFFA-TASSELED-1.webp';
import img1_2 from '../../1. Horeca Seating/Bar Chairs/RFBC0101/ZEFFA-TASSELED-3.webp';
import img1_3 from '../../1. Horeca Seating/Bar Chairs/RFBC0101/ZEFFA-TASSELED-4.webp';
import img1_4 from '../../1. Horeca Seating/Bar Chairs/RFBC0101/ZEFFA-TASSELED-5.webp';
import img1_5 from '../../1. Horeca Seating/Bar Chairs/RFBC0101/ZEFFA-TASSELED2.webp';
import img2_1 from '../../1. Horeca Seating/Bar Chairs/RFBC0102/VARRENS-bar-1.webp';
import img2_2 from '../../1. Horeca Seating/Bar Chairs/RFBC0102/VARRENS-bar-2.webp';
import img2_3 from '../../1. Horeca Seating/Bar Chairs/RFBC0102/VARRENS-bar-3.webp';
import img2_4 from '../../1. Horeca Seating/Bar Chairs/RFBC0102/VARRENS-bar-4.webp';
import img2_5 from '../../1. Horeca Seating/Bar Chairs/RFBC0102/VARRENS-bar-5.webp';
import img3_1 from '../../1. Horeca Seating/Bar Chairs/RFBC0103/TADEMA-1.webp';
import img3_2 from '../../1. Horeca Seating/Bar Chairs/RFBC0103/TADEMA-2.webp';
import img3_3 from '../../1. Horeca Seating/Bar Chairs/RFBC0103/TADEMA-3.webp';
import img3_4 from '../../1. Horeca Seating/Bar Chairs/RFBC0103/TADEMA-4.webp';
import img3_5 from '../../1. Horeca Seating/Bar Chairs/RFBC0103/TADEMA-5.webp';
import img4_1 from '../../1. Horeca Seating/Bar Chairs/RFBC0104/PETNA-BAR-1.webp';
import img4_2 from '../../1. Horeca Seating/Bar Chairs/RFBC0104/PETNA-BAR-2.webp';
import img4_3 from '../../1. Horeca Seating/Bar Chairs/RFBC0104/PETNA-BAR-4.webp';
import img4_4 from '../../1. Horeca Seating/Bar Chairs/RFBC0104/PETNA-BAR-5.webp';
import img4_5 from '../../1. Horeca Seating/Bar Chairs/RFBC0104/PETNA-BAR-6.webp';
import img5_1 from '../../1. Horeca Seating/Bar Chairs/RFBC0105/OVETU-1.webp';
import img5_2 from '../../1. Horeca Seating/Bar Chairs/RFBC0105/OVETU-2.webp';
import img5_3 from '../../1. Horeca Seating/Bar Chairs/RFBC0105/OVETU-3.webp';
import img6_1 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205 (1).webp';
import img6_2 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205 (2).webp';
import img6_3 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205 (3).webp';
import img6_4 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205 (4).webp';
import img6_5 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205 (5).webp';
import img6_6 from '../../1. Horeca Seating/Indoor Chairs/New folder/Corrigan+Studio+Solid+Wood+Dining+Chairs+(Set+of+2)+–+PU+Leather+Cushioned+Seat+&+Low+Open+Back,+Mid‑Century+Modern-1860420205.webp';
import img7_1 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_01_3072x.webp';
import img7_2 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_02_3072x.webp';
import img7_3 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_03_3072x.webp';
import img7_4 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_04_3072x.webp';
import img7_5 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_05_3072x.webp';
import img7_6 from '../../1. Horeca Seating/Indoor Chairs/New folder (2)/industry_west_product_joi_diningchair_black_06_3072x.webp';
import img8_1 from '../../1. Horeca Seating/Indoor Chairs/New folder (3)/1_ad3b5412-4390-483d-977e-8e9ea6d2210b.webp';
import img8_2 from '../../1. Horeca Seating/Indoor Chairs/New folder (3)/3_f05f9d8e-9b99-453f-81ec-ef2bc8a051eb.webp';
import img8_3 from '../../1. Horeca Seating/Indoor Chairs/New folder (3)/4_582ccbb3-9d9f-42f2-9291-b592442e547e.webp';
import img8_4 from '../../1. Horeca Seating/Indoor Chairs/New folder (3)/5_7c78e3fc-7d85-4e3a-a389-e5e959a51d28.webp';
import img8_5 from '../../1. Horeca Seating/Indoor Chairs/New folder (3)/rattan-dining-chair-thatcooliving-that-cool-living-detjer.webp';
import img9_1 from '../../1. Horeca Seating/Indoor Chairs/New folder (4)/1_1418972c-dc3a-44ad-a0d2-e0238fcba234.webp';
import img9_2 from '../../1. Horeca Seating/Indoor Chairs/New folder (4)/6_c2c28145-6c6e-4460-a4b3-803291f3c13c.webp';
import img9_3 from '../../1. Horeca Seating/Indoor Chairs/New folder (4)/oki-nami-chair-black_0aa5101a-dece-4e22-99b2-8c45ba8d2981.webp';
import img10_1 from '../../1. Horeca Seating/Indoor Chairs/New folder (5)/10_c0c5c85f-3f43-4bb3-bcd1-a6e8d756d76b.webp';
import img10_2 from '../../1. Horeca Seating/Indoor Chairs/New folder (5)/2_2bb9fff3-81a8-4a07-9152-72f3c0142764.webp';
import img10_3 from '../../1. Horeca Seating/Indoor Chairs/New folder (5)/4_510619b1-56b4-4c8d-be0c-aa4fcfc82234.webp';
import img10_4 from '../../1. Horeca Seating/Indoor Chairs/New folder (5)/7_6cfb8d33-ac7a-4b41-a45c-a3f2fd488d7c.webp';
import img10_5 from '../../1. Horeca Seating/Indoor Chairs/New folder (5)/11_219c71c3-9e8a-44b0-a7b8-a0fd31c60059.webp';
import img11_1 from '../../1. Horeca Seating/Lounge Chairs/New folder/ZARAX-1-scaled-1.webp';
import img11_2 from '../../1. Horeca Seating/Lounge Chairs/New folder/ZARAX-2.webp';
import img11_3 from '../../1. Horeca Seating/Lounge Chairs/New folder/ZARAX-3-scaled-1.webp';
import img11_4 from '../../1. Horeca Seating/Lounge Chairs/New folder/ZARAX-4.webp';
import img11_5 from '../../1. Horeca Seating/Lounge Chairs/New folder/ZARAX-5.webp';
import img12_1 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-1-1.webp';
import img12_2 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-2.webp';
import img12_3 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-3.webp';
import img12_4 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-4.webp';
import img12_5 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-5.webp';
import img12_6 from '../../1. Horeca Seating/Lounge Chairs/New folder (2)/UGITI-6.webp';
import img13_1 from '../../1. Horeca Seating/Lounge Chairs/New folder (3)/TETRA-1-scaled-1.webp';
import img13_2 from '../../1. Horeca Seating/Lounge Chairs/New folder (3)/TETRA-2-scaled-1.webp';
import img13_3 from '../../1. Horeca Seating/Lounge Chairs/New folder (3)/TETRA-3-scaled-1.webp';
import img13_4 from '../../1. Horeca Seating/Lounge Chairs/New folder (3)/TETRA-5-scaled-1.webp';
import img13_5 from '../../1. Horeca Seating/Lounge Chairs/New folder (3)/TETRA-6-scaled-1.webp';
import img14_1 from '../../1. Horeca Seating/Lounge Chairs/New folder (4)/RULIG-WICKER-1.webp';
import img14_2 from '../../1. Horeca Seating/Lounge Chairs/New folder (4)/RULIG-WICKER-3.webp';
import img14_3 from '../../1. Horeca Seating/Lounge Chairs/New folder (4)/RULIG-WICKER-4.webp';
import img14_4 from '../../1. Horeca Seating/Lounge Chairs/New folder (4)/RULIG-WICKER-5.webp';
import img14_5 from '../../1. Horeca Seating/Lounge Chairs/New folder (4)/RULIG-WICKER-6.webp';
import img15_1 from '../../1. Horeca Seating/Lounge Chairs/New folder (5)/ROFFO-1.webp';
import img15_2 from '../../1. Horeca Seating/Lounge Chairs/New folder (5)/ROFFO-2.webp';
import img15_3 from '../../1. Horeca Seating/Lounge Chairs/New folder (5)/ROFFO-3.webp';
import img15_4 from '../../1. Horeca Seating/Lounge Chairs/New folder (5)/ROFFO-4.webp';
import img16_1 from '../../1. Horeca Seating/Poufs/New folder/DOOR-TABURE-1-scaled-1.webp';
import img16_2 from '../../1. Horeca Seating/Poufs/New folder/DOOR-TABURE-2-scaled-1.webp';
import img17_1 from '../../1. Horeca Seating/Poufs/New folder (2)/MAYZAR-1-scaled-1.webp';
import img17_2 from '../../1. Horeca Seating/Poufs/New folder (2)/MAYZAR-2-scaled-1.webp';
import img17_3 from '../../1. Horeca Seating/Poufs/New folder (2)/MAYZAR-3-scaled-1.webp';
import img18_1 from '../../1. Horeca Seating/Poufs/New folder (3)/SANSA-SMALL-1-scaled-2.webp';
import img18_2 from '../../1. Horeca Seating/Poufs/New folder (3)/SANSA-SMALL-2-scaled-2.webp';
import img19_1 from '../../1. Horeca Seating/Poufs/New folder (4)/GRAZ-SIRIPE-1-scaled-1.webp';
import img20_1 from '../../1. Horeca Seating/Poufs/New folder (5)/urun-sugar-pouf-puf-01.webp';
import img21_1 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0101/ZOPUM-1.webp';
import img21_2 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0101/ZOPUM-2.webp';
import img21_3 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0101/ZOPUM-3.webp';
import img21_4 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0101/ZOPUM-4.webp';
import img21_5 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0101/ZOPUM-5.webp';
import img22_1 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0102/YETAB-1.webp';
import img22_2 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0102/YETAB-2.webp';
import img22_3 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0102/YETAB-3.webp';
import img22_4 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0102/YETAB-4.webp';
import img22_5 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0102/YETAB-5.webp';
import img23_1 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0103/WILED-1.webp';
import img23_2 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0103/WILED-2.webp';
import img23_3 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0103/WILED-3.webp';
import img23_4 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0103/WILED-4.webp';
import img24_1 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0104/VENAW-1.webp';
import img24_2 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0104/VENAW-2.webp';
import img24_3 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0104/VENAW-3.webp';
import img24_4 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0104/VENAW-4.webp';
import img24_5 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0104/VENAW-5.webp';
import img25_1 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0105/ULATE-C-1.webp';
import img25_2 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0105/ULATE-C-2.webp';
import img25_3 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0105/ULATE-C-3.webp';
import img25_4 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0105/ULATE-C-4.webp';
import img25_5 from '../../1. Horeca Seating/Sofas, Benches & Booths/RFSBB0105/ULATE-C-5.webp';
import img26_1 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-2-seater-bar-table-in-natural-finish-kylie-acacia-wood-2-seater-bar-table-in-natur-4ub0yi.webp';
import img26_2 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-4-seater-bar-table-in-natural-finish-kylie-acacia-wood-4-seater-bar-table-in-natur-bb5te2.jpg';
import img26_3 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-4-seater-bar-table-in-natural-finish-kylie-acacia-wood-4-seater-bar-table-in-natur-jh3yiq.webp';
import img26_4 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-4-seater-bar-table-in-natural-finish-kylie-acacia-wood-4-seater-bar-table-in-natur-k8ojef.webp';
import img26_5 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-4-seater-bar-table-in-natural-finish-kylie-acacia-wood-4-seater-bar-table-in-natur-saoz16.webp';
import img26_6 from '../../2. Horeca Tables/Bar Tables/New folder/kylie-acacia-wood-4-seater-bar-table-in-natural-finish-kylie-acacia-wood-4-seater-bar-table-in-natur-trjztq.jpg';
import img27_1 from '../../2. Horeca Tables/Bar Tables/New folder (2)/M-590-WALNUT-2-kopya-scaled-2.webp';
import img27_2 from '../../2. Horeca Tables/Bar Tables/New folder (2)/M-590-WALNUT-3-kopya-scaled-1.webp';
import img28_1 from '../../2. Horeca Tables/Bar Tables/New folder (3)/mesa-alta-redonda-em-madeira-de-acacia-asteca (1).webp';
import img28_2 from '../../2. Horeca Tables/Bar Tables/New folder (3)/mesa-alta-redonda-em-madeira-de-acacia-asteca (2).webp';
import img28_3 from '../../2. Horeca Tables/Bar Tables/New folder (3)/mesa-alta-redonda-em-madeira-de-acacia-asteca.webp';
import img28_4 from '../../2. Horeca Tables/Bar Tables/New folder (3)/mesa-de-bar-alta-quadrada-em-madeira-de-acacia-asteca (1).webp';
import img28_5 from '../../2. Horeca Tables/Bar Tables/New folder (3)/mesa-de-bar-alta-quadrada-em-madeira-de-acacia-asteca.webp';
import img29_1 from '../../2. Horeca Tables/Bar Tables/New folder (4)/Monologue-London-GTV-Thonet-Cognac-Lifestyle.webp';
import img29_2 from '../../2. Horeca Tables/Bar Tables/New folder (4)/Monologue-London-GTV-Thonet-Cognac-Table-Detail.webp';
import img29_3 from '../../2. Horeca Tables/Bar Tables/New folder (4)/Monologue-London-GTV-Thonet-Cognac-Table-Marble-Top.webp';
import img30_1 from '../../2. Horeca Tables/Ceramic Tables/New folder/MC-190-PRS-07-1-scaled-1.webp';
import img30_2 from '../../2. Horeca Tables/Ceramic Tables/New folder/MC-190-PRS-07-2-scaled-1.webp';
import img30_3 from '../../2. Horeca Tables/Ceramic Tables/New folder/MC-190-PRS-07-3-scaled-1.webp';
import img31_1 from '../../2. Horeca Tables/Ceramic Tables/New folder (2)/MC-137-PRS-07-1-scaled-1.webp';
import img31_2 from '../../2. Horeca Tables/Ceramic Tables/New folder (2)/MC-137-PRS-07-2.webp';
import img31_3 from '../../2. Horeca Tables/Ceramic Tables/New folder (2)/MC-137-PRS-07-3-scaled-1.webp';
import img31_4 from '../../2. Horeca Tables/Ceramic Tables/New folder (2)/MC-137-PRS-07-scaled-2.webp';
import img32_1 from '../../2. Horeca Tables/Ceramic Tables/New folder (3)/MC-131-S4-scaled-1.webp';
import img33_1 from '../../2. Horeca Tables/Ceramic Tables/New folder (4)/MG-100-S-4-1-scaled-1.webp';
import img33_2 from '../../2. Horeca Tables/Ceramic Tables/New folder (4)/MG-100-S-4-2-scaled-2.webp';
import img34_1 from '../../2. Horeca Tables/Ceramic Tables/New folder (5)/MC-190-PRS-6-1-scaled-1.webp';
import img34_2 from '../../2. Horeca Tables/Ceramic Tables/New folder (5)/MC-190-PRS-6-2-scaled-1.webp';
import img34_3 from '../../2. Horeca Tables/Ceramic Tables/New folder (5)/MC-190-PRS-6-3-scaled-1.webp';
import img35_1 from '../../2. Horeca Tables/Marble Tables/ILBT0001/Pedestal+Dining+Table-255973401 (1).webp';
import img35_2 from '../../2. Horeca Tables/Marble Tables/ILBT0001/Pedestal+Dining+Table-255973401.webp';
import img36_1 from '../../2. Horeca Tables/Marble Tables/ILBT0010/30bistro-wh_blk_01-Photoroom.png';
import img36_2 from '../../2. Horeca Tables/Marble Tables/ILBT0010/30bistro-wh_blk_01.webp';
import img36_3 from '../../2. Horeca Tables/Marble Tables/ILBT0010/RitaChair_sq06.webp';
import img37_1 from '../../2. Horeca Tables/Marble Tables/ILBT0032/Emmo+Round+Faux+Marble+Dining+Table (1).webp';
import img37_2 from '../../2. Horeca Tables/Marble Tables/ILBT0032/Emmo+Round+Faux+Marble+Dining+Table (2).webp';
import img37_3 from '../../2. Horeca Tables/Marble Tables/ILBT0032/Emmo+Round+Faux+Marble+Dining+Table-Photoroom.png';
import img37_4 from '../../2. Horeca Tables/Marble Tables/ILBT0032/Emmo+Round+Faux+Marble+Dining+Table.webp';
import img38_1 from '../../2. Horeca Tables/Marble Tables/ILBT0054/ToposW_044-1-scaled.jpg';
import img38_2 from '../../2. Horeca Tables/Marble Tables/ILBT0054/ToposW_045-scaled-Photoroom.png';
import img38_3 from '../../2. Horeca Tables/Marble Tables/ILBT0054/ToposW_045-scaled.jpg';
import img38_4 from '../../2. Horeca Tables/Marble Tables/ILBT0054/ToposW_047-scaled.jpg';
import img39_1 from '../../2. Horeca Tables/Marble Tables/New folder (11)/7a87470c-cc25-4101-bfff-18af21a46ccc.png';
import img40_1 from '../../2. Horeca Tables/Wooden Tables/ILBT0002/cafe-table-round-top-weighted-base-ca-rtabsw605-4a-t-851668_2000x.webp';
import img41_1 from '../../2. Horeca Tables/Wooden Tables/ILBT0004/cafe-table-round-top-x-base-ca-rtabsx604-4a-t-219149_2000x.webp';
import img42_1 from '../../2. Horeca Tables/Wooden Tables/ILBT0008/cafe-table-rectangular-top-weighted-two-stem-base-ca-ctabswt604-4a-t-549678_2000x.webp';
import img43_1 from '../../2. Horeca Tables/Wooden Tables/ILBT0017/2553576.jpg';
import img44_1 from '../../2. Horeca Tables/Wooden Tables/ILBT0020/124589-flip-top-nesting-training-table-1.webp';
import img45_1 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/ChatGPT Image Feb 16, 2026, 03_00_53 PM.png';
import img45_2 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey1_2000x.webp';
import img45_3 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey2_2000x.webp';
import img45_4 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey3_2000x.webp';
import img45_5 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey4_2000x.jpg';
import img45_6 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey5_2000x.jpg';
import img45_7 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey6_2000x.jpg';
import img45_8 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey7_2000x.jpg';
import img45_9 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey8_2000x.webp';
import img45_10 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0001 DOBRE/SaraiDiningChair_BelfastHeatherGrey9_2000x.webp';
import img46_1 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/ChatGPT Image Feb 16, 2026, 03_09_16 PM.png';
import img46_2 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_1_2000x.webp';
import img46_3 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_2_2000x.webp';
import img46_4 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_3_2000x.webp';
import img46_5 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_4_2000x.webp';
import img46_6 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_5_2000x.webp';
import img46_7 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_6_2000x.webp';
import img46_8 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_7_2000x.jpg';
import img46_9 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_8_2000x.webp';
import img46_10 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0002 SENOM/porto_outdoor_dining_chair_9_2000x.webp';
import img47_1 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (1).webp';
import img47_2 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (2).webp';
import img47_3 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (3).webp';
import img47_4 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (4).webp';
import img47_5 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (5).webp';
import img47_6 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (6).webp';
import img47_7 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (7).webp';
import img47_8 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (8).webp';
import img47_9 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (9).webp';
import img47_10 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (10).webp';
import img47_11 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (11).webp';
import img47_12 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (12).webp';
import img47_13 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (13).webp';
import img47_14 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (14).webp';
import img47_15 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (15).webp';
import img47_16 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (16).webp';
import img47_17 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (17).webp';
import img47_18 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (18).webp';
import img47_19 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (19).webp';
import img47_20 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (20).webp';
import img47_21 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (21).webp';
import img47_22 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (22).webp';
import img47_23 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (23).webp';
import img47_24 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (24).webp';
import img47_25 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (25).webp';
import img47_26 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (26).webp';
import img47_27 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (27).webp';
import img47_28 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (28).webp';
import img47_29 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (29).webp';
import img47_30 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (30).webp';
import img47_31 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (31).webp';
import img47_32 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (32).webp';
import img47_33 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (33).webp';
import img47_34 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (34).webp';
import img47_35 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (35).webp';
import img47_36 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (36).webp';
import img47_37 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair (37).webp';
import img47_38 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/Abra+Powder+Coated+Steel+Outdoor+Stacking+Dining+Side+Chair.webp';
import img47_39 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0004 ABRA/ChatGPT Image Feb 16, 2026, 05_14_32 PM.png';
import img48_1 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/ChatGPT Image Mar 29, 2026, 01_31_02 PM.png';
import img48_2 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (1).webp';
import img48_3 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (2).webp';
import img48_4 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (3).webp';
import img48_5 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (4).webp';
import img48_6 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (5).webp';
import img48_7 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (6).webp';
import img48_8 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (7).webp';
import img48_9 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (8).webp';
import img48_10 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (9).webp';
import img48_11 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891 (10).webp';
import img48_12 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1941297891.webp';
import img48_13 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (1).webp';
import img48_14 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (2).webp';
import img48_15 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (3).webp';
import img48_16 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (4).webp';
import img48_17 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (5).webp';
import img48_18 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (6).webp';
import img48_19 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (7).webp';
import img48_20 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (8).webp';
import img48_21 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (9).webp';
import img48_22 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185 (10).webp';
import img48_23 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0011 SORIN/Zechariah+Outdoor+PE+Rattan+Stacking+Dining+Chairs-1945362185.webp';
import img49_1 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/ChatGPT Image Mar 29, 2026, 01_35_21 PM.png';
import img49_2 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (1).webp';
import img49_3 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (2).webp';
import img49_4 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (3).webp';
import img49_5 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (4).webp';
import img49_6 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (5).webp';
import img49_7 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (6).webp';
import img49_8 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (7).webp';
import img49_9 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (8).webp';
import img49_10 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (9).webp';
import img49_11 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324 (10).webp';
import img49_12 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602324.webp';
import img49_13 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (1).webp';
import img49_14 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (2).webp';
import img49_15 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (3).webp';
import img49_16 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (4).webp';
import img49_17 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (5).webp';
import img49_18 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (6).webp';
import img49_19 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (7).webp';
import img49_20 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (8).webp';
import img49_21 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (9).webp';
import img49_22 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (10).webp';
import img49_23 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (11).webp';
import img49_24 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (12).webp';
import img49_25 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (13).webp';
import img49_26 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325 (14).webp';
import img49_27 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602325.webp';
import img49_28 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (1).webp';
import img49_29 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (2).webp';
import img49_30 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (3).webp';
import img49_31 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (4).webp';
import img49_32 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (5).webp';
import img49_33 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (6).webp';
import img49_34 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (7).webp';
import img49_35 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (8).webp';
import img49_36 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (9).webp';
import img49_37 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (10).webp';
import img49_38 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (11).webp';
import img49_39 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (12).webp';
import img49_40 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (13)-Photoroom.png';
import img49_41 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (13).webp';
import img49_42 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327 (14).webp';
import img49_43 from '../../4. Outdoor Furniture/Outdoor Chairs/ILMC0013 ROMIX/Modern+Stackable+Dining+Chair+Set+with+Breathable+Backrest+and+Sturdy+Metal+Legs+for+Outdoor+Use-1258602327.webp';
import img50_1 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder/DESOYAN-1-scaled-2.webp';
import img50_2 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder/DESOYAN-2-scaled-2.webp';
import img50_3 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder/DESOYAN-3-scaled-3.webp';
import img51_1 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-1-scaled-2.webp';
import img51_2 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-3-scaled-2.webp';
import img51_3 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-4-scaled-1.webp';
import img51_4 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-5.webp';
import img51_5 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-6-scaled-2.webp';
import img51_6 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (2)/MIRA-BANK-scaled-1.webp';
import img52_1 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (3)/PROYAN-1-1-scaled-1.webp';
import img52_2 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (3)/PROYAN-2-1-scaled-1.webp';
import img52_3 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (3)/PROYAN-3-scaled-1.webp';
import img52_4 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (3)/PROYAN-4-1-scaled-1.webp';
import img52_5 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (3)/PROYAN-5-1-scaled-1.webp';
import img53_1 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-2-scaled-1.webp';
import img53_2 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-3-scaled-1.webp';
import img53_3 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-4-scaled-1.webp';
import img53_4 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-5-scaled-1.webp';
import img53_5 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-6-scaled-1.webp';
import img53_6 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-7-scaled-1.webp';
import img53_7 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-8-scaled-1.webp';
import img53_8 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (4)/SIRIUS-ROPE-BERGERE-scaled-1.webp';
import img54_1 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-2-scaled-1.webp';
import img54_2 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-3-scaled-1.webp';
import img54_3 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-4-scaled-1.webp';
import img54_4 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-5-scaled-1.webp';
import img54_5 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-6-scaled-1.webp';
import img54_6 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-7-scaled-1.webp';
import img54_7 from '../../4. Outdoor Furniture/Outdoor Sofas & Benches/New folder (5)/HOLLOW-9-scaled-1.webp';

export interface Product {
  id: number;
  name: string;
  code: string;
  slug: string;
  category: string;
  image: string;
  images: string[];
  colors: string[];
  bgColor: string;
  price: number;
  material: string;
}

export const allProducts: Product[] = [
  {
    id: 1,
    name: "Zeffa Luxe Tasselled Swivel Bar Chair",
    code: "RFBC0101",
    slug: "zeffa-luxe-tasselled-swivel-bar-chair",
    category: "Bar Chairs",
    image: img1_1,
    images: [img1_1, img1_2, img1_3, img1_4, img1_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 96,
    material: "Velvet & Powder-Coated Steel"
  },
  {
    id: 2,
    name: "Varrens Contemporary Upholstered Bar Chair",
    code: "RFBC0102",
    slug: "varrens-contemporary-upholstered-bar-chair",
    category: "Bar Chairs",
    image: img2_1,
    images: [img2_1, img2_2, img2_3, img2_4, img2_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 103,
    material: "Upholstered Fabric & Steel"
  },
  {
    id: 3,
    name: "Tadema Classic Round Pedestal Bar Stool",
    code: "RFBC0103",
    slug: "tadema-classic-round-pedestal-bar-stool",
    category: "Bar Chairs",
    image: img3_1,
    images: [img3_1, img3_2, img3_3, img3_4, img3_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 110,
    material: "Solid Wood & Cast Iron"
  },
  {
    id: 4,
    name: "Petna Heritage Wooden Bar Chair",
    code: "RFBC0104",
    slug: "petna-heritage-wooden-bar-chair",
    category: "Bar Chairs",
    image: img4_1,
    images: [img4_1, img4_2, img4_3, img4_4, img4_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 117,
    material: "Solid Sheesham Wood"
  },
  {
    id: 5,
    name: "Ovetu Minimal Wooden Bar Stool",
    code: "RFBC0105",
    slug: "ovetu-minimal-wooden-bar-stool",
    category: "Bar Chairs",
    image: img5_1,
    images: [img5_1, img5_2, img5_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 124,
    material: "Solid Teak Wood"
  },
  {
    id: 6,
    name: "Arden Solid Wood Dining Chair",
    code: "RFIC0101",
    slug: "arden-solid-wood-dining-chair",
    category: "Indoor Chairs",
    image: img6_1,
    images: [img6_1, img6_2, img6_3, img6_4, img6_5, img6_6],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 131,
    material: "Solid Wood & PU Leather"
  },
  {
    id: 7,
    name: "Joi Minimal Black Dining Chair",
    code: "RFIC0102",
    slug: "joi-minimal-black-dining-chair",
    category: "Indoor Chairs",
    image: img7_5,
    images: [img7_1, img7_2, img7_3, img7_4, img7_5, img7_6],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 138,
    material: "Powder-Coated Steel"
  },
  {
    id: 8,
    name: "Rattan Heritage Cane Dining Chair",
    code: "RFIC0103",
    slug: "rattan-heritage-cane-dining-chair",
    category: "Indoor Chairs",
    image: img8_1,
    images: [img8_1, img8_2, img8_3, img8_4, img8_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 145,
    material: "Natural Rattan & Cane"
  },
  {
    id: 9,
    name: "Nami Contemporary Black Dining Chair",
    code: "RFIC0104",
    slug: "nami-contemporary-black-dining-chair",
    category: "Indoor Chairs",
    image: img9_1,
    images: [img9_1, img9_2, img9_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 152,
    material: "Bentwood & Steel Frame"
  },
  {
    id: 10,
    name: "Elara Upholstered Wooden Dining Chair",
    code: "RFIC0105",
    slug: "elara-upholstered-wooden-dining-chair",
    category: "Indoor Chairs",
    image: img10_1,
    images: [img10_1, img10_2, img10_3, img10_4, img10_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 159,
    material: "Solid Oak & Upholstered Fabric"
  },
  {
    id: 11,
    name: "Zarax Boucle Lounge Chair with Side Table",
    code: "RFLC0101",
    slug: "zarax-boucle-lounge-chair-with-side-table",
    category: "Lounge Chairs",
    image: img11_3,
    images: [img11_1, img11_2, img11_3, img11_4, img11_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 166,
    material: "Bouclé Fabric & Solid Wood"
  },
  {
    id: 12,
    name: "Ugiti Leather Tub Lounge Chair",
    code: "RFLC0102",
    slug: "ugiti-leather-tub-lounge-chair",
    category: "Lounge Chairs",
    image: img12_1,
    images: [img12_1, img12_2, img12_3, img12_4, img12_5, img12_6],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 173,
    material: "Full-Grain Leather & Steel"
  },
  {
    id: 13,
    name: "Tetra Sculptural Velvet Lounge Chair",
    code: "RFLC0103",
    slug: "tetra-sculptural-velvet-lounge-chair",
    category: "Lounge Chairs",
    image: img13_3,
    images: [img13_1, img13_2, img13_3, img13_4, img13_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 180,
    material: "Velvet & Hardwood Frame"
  },
  {
    id: 14,
    name: "Rulig Cane-Panel Lounge Armchair",
    code: "RFLC0104",
    slug: "rulig-cane-panel-lounge-armchair",
    category: "Lounge Chairs",
    image: img14_1,
    images: [img14_1, img14_2, img14_3, img14_4, img14_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 187,
    material: "Natural Wicker & Teak"
  },
  {
    id: 15,
    name: "Roffo Contemporary Leather Lounge Chair",
    code: "RFLC0105",
    slug: "roffo-contemporary-leather-lounge-chair",
    category: "Lounge Chairs",
    image: img15_1,
    images: [img15_1, img15_2, img15_3, img15_4],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 194,
    material: "Top-Grain Leather & Chrome"
  },
  {
    id: 16,
    name: "Oslo Padded Timber Stool",
    code: "RFPF0101",
    slug: "oslo-padded-timber-stool",
    category: "Poufs",
    image: img16_1,
    images: [img16_1, img16_2],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 201,
    material: "Solid Timber & Padded Fabric"
  },
  {
    id: 17,
    name: "Rustic Wooden Barrel Storage Ottoman",
    code: "RFPF0102",
    slug: "rustic-wooden-barrel-storage-ottoman",
    category: "Poufs",
    image: img17_1,
    images: [img17_1, img17_2, img17_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 208,
    material: "Reclaimed Wood & Iron"
  },
  {
    id: 18,
    name: "Sansa Metal Framed Stool",
    code: "RFPF0103",
    slug: "sansa-metal-framed-stool",
    category: "Poufs",
    image: img18_2,
    images: [img18_1, img18_2],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 215,
    material: "Powder-Coated Steel & Fabric"
  },
  {
    id: 19,
    name: "Graz Fluted Velvet Ottoman",
    code: "RFPF0104",
    slug: "graz-fluted-velvet-ottoman",
    category: "Poufs",
    image: img19_1,
    images: [img19_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 222,
    material: "Fluted Velvet & Hardwood"
  },
  {
    id: 20,
    name: "Sugar Zebra Print Pouf",
    code: "RFPF0105",
    slug: "sugar-zebra-print-pouf",
    category: "Poufs",
    image: img20_1,
    images: [img20_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 229,
    material: "Printed Fabric & Foam Core"
  },
  {
    id: 21,
    name: "Zopum Channel-Tufted U-Shape Sofa",
    code: "RFSBB0101",
    slug: "zopum-channel-tufted-u-shape-sofa",
    category: "Sofas, Benches & Booths",
    image: img21_1,
    images: [img21_1, img21_2, img21_3, img21_4, img21_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 236,
    material: "Velvet & Kiln-Dried Hardwood"
  },
  {
    id: 22,
    name: "Yetab Fluted Upholstered Bench",
    code: "RFSBB0102",
    slug: "yetab-fluted-upholstered-bench",
    category: "Sofas, Benches & Booths",
    image: img22_1,
    images: [img22_1, img22_2, img22_3, img22_4, img22_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 93,
    material: "Upholstered Fabric & Steel Legs"
  },
  {
    id: 23,
    name: "Wiled Curved Art Deco Sofa",
    code: "RFSBB0103",
    slug: "wiled-curved-art-deco-sofa",
    category: "Sofas, Benches & Booths",
    image: img23_1,
    images: [img23_1, img23_2, img23_3, img23_4],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 100,
    material: "Velvet & Solid Wood Frame"
  },
  {
    id: 24,
    name: "Venaw Modular Slatted Banquette",
    code: "RFSBB0104",
    slug: "venaw-modular-slatted-banquette",
    category: "Sofas, Benches & Booths",
    image: img24_1,
    images: [img24_1, img24_2, img24_3, img24_4, img24_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 107,
    material: "Slatted Teak & Upholstery"
  },
  {
    id: 25,
    name: "Ulate Curved Sectional Sofa",
    code: "RFSBB0105",
    slug: "ulate-curved-sectional-sofa",
    category: "Sofas, Benches & Booths",
    image: img25_1,
    images: [img25_1, img25_2, img25_3, img25_4, img25_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 114,
    material: "High-Density Foam & Fabric"
  },
  {
    id: 26,
    name: "Kylie Acacia Wood Bar Table",
    code: "RFBT0101",
    slug: "kylie-acacia-wood-bar-table",
    category: "Bar Tables",
    image: img26_1,
    images: [img26_1, img26_2, img26_3, img26_4, img26_5, img26_6],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 121,
    material: "Solid Acacia Wood"
  },
  {
    id: 27,
    name: "Walnut Bistro High Table",
    code: "RFBT0102",
    slug: "walnut-bistro-high-table",
    category: "Bar Tables",
    image: img27_1,
    images: [img27_1, img27_2],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 128,
    material: "Walnut Veneer & Steel"
  },
  {
    id: 28,
    name: "Asteca Acacia Wood Bar Table",
    code: "RFBT0103",
    slug: "asteca-acacia-wood-bar-table",
    category: "Bar Tables",
    image: img28_1,
    images: [img28_1, img28_2, img28_3, img28_4, img28_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 135,
    material: "Solid Acacia Wood"
  },
  {
    id: 29,
    name: "Thonet Cognac & Black Marble Bar Table",
    code: "RFBT0104",
    slug: "thonet-cognac-black-marble-bar-table",
    category: "Bar Tables",
    image: img29_1,
    images: [img29_1, img29_2, img29_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 142,
    material: "Marble Top & Bentwood"
  },
  {
    id: 30,
    name: "MC-190 Glam Ceramic Bistro Table",
    code: "RFCT0101",
    slug: "mc-190-glam-ceramic-bistro-table",
    category: "Ceramic Tables",
    image: img30_1,
    images: [img30_1, img30_2, img30_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 149,
    material: "Ceramic Top & Brass Frame"
  },
  {
    id: 31,
    name: "MC-137 Ceramic & Wood Bistro Table",
    code: "RFCT0102",
    slug: "mc-137-ceramic-wood-bistro-table",
    category: "Ceramic Tables",
    image: img31_1,
    images: [img31_1, img31_2, img31_3, img31_4],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 156,
    material: "Ceramic & Solid Wood"
  },
  {
    id: 32,
    name: "MC-131 Ceramic & Wood-Framed Bistro Table",
    code: "RFCT0103",
    slug: "mc-131-ceramic-wood-framed-bistro-table",
    category: "Ceramic Tables",
    image: img32_1,
    images: [img32_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 163,
    material: "Ceramic & Hardwood Frame"
  },
  {
    id: 33,
    name: "MG-100 Rose Gold Ceramic Bistro Table",
    code: "RFCT0104",
    slug: "mg-100-rose-gold-ceramic-bistro-table",
    category: "Ceramic Tables",
    image: img33_1,
    images: [img33_1, img33_2],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 170,
    material: "Ceramic & Rose Gold Steel"
  },
  {
    id: 34,
    name: "MC-190 Ribbed Brass Edge Ceramic Bistro Table",
    code: "RFCT0105",
    slug: "mc-190-ribbed-brass-edge-ceramic-bistro-table",
    category: "Ceramic Tables",
    image: img34_1,
    images: [img34_1, img34_2, img34_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 177,
    material: "Ceramic & Brass Trim"
  },
  {
    id: 35,
    name: "Minimalist Round Marble Pedestal Table",
    code: "ILBT0001",
    slug: "minimalist-round-marble-pedestal-table",
    category: "Marble Tables",
    image: img35_1,
    images: [img35_1, img35_2],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 184,
    material: "Natural Marble & Steel"
  },
  {
    id: 36,
    name: "Wireframe Pedestal Round Marble Bistro Table",
    code: "ILBT0010",
    slug: "wireframe-pedestal-round-marble-bistro-table",
    category: "Marble Tables",
    image: img36_1,
    images: [img36_1, img36_2, img36_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 191,
    material: "Marble & Wireframe Steel"
  },
  {
    id: 37,
    name: "Emmo Round Faux Marble Wireframe Table",
    code: "ILBT0032",
    slug: "emmo-round-faux-marble-wireframe-table",
    category: "Marble Tables",
    image: img37_3,
    images: [img37_1, img37_2, img37_3, img37_4],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 198,
    material: "Faux Marble & Powder-Coated Steel"
  },
  {
    id: 38,
    name: "Fluted Brass & Black Marble Bistro Table",
    code: "ILBT0054",
    slug: "fluted-brass-black-marble-bistro-table",
    category: "Marble Tables",
    image: img38_1,
    images: [img38_1, img38_2, img38_3, img38_4],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 205,
    material: "Black Marble & Brass"
  },
  {
    id: 39,
    name: "Terrazzo Square Cone-Base Bistro Table",
    code: "ILBT0011",
    slug: "terrazzo-square-cone-base-bistro-table",
    category: "Marble Tables",
    image: img39_1,
    images: [img39_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 212,
    material: "Terrazzo & Concrete Base"
  },
  {
    id: 40,
    name: "Weighted Base Round Oak Veneer Café Table",
    code: "ILBT0002",
    slug: "weighted-base-round-oak-veneer-caf-table",
    category: "Wooden Tables",
    image: img40_1,
    images: [img40_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 219,
    material: "Oak Veneer & Cast Iron Base"
  },
  {
    id: 41,
    name: "X-Base Round Oak Veneer Café Table",
    code: "ILBT0004",
    slug: "x-base-round-oak-veneer-caf-table",
    category: "Wooden Tables",
    image: img41_1,
    images: [img41_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 226,
    material: "Oak Veneer & Chrome Base"
  },
  {
    id: 42,
    name: "Two-Stem Rectangular Oak Veneer Café Table",
    code: "ILBT0008",
    slug: "two-stem-rectangular-oak-veneer-caf-table",
    category: "Wooden Tables",
    image: img42_1,
    images: [img42_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 233,
    material: "Oak Veneer & Dual Steel Stems"
  },
  {
    id: 43,
    name: "Urban Outdoor Perforated Round Bistro Table",
    code: "ILBT0017",
    slug: "urban-outdoor-perforated-round-bistro-table",
    category: "Wooden Tables",
    image: img43_1,
    images: [img43_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 90,
    material: "Perforated Steel & Powder Coat"
  },
  {
    id: 44,
    name: "Flip-Top Nesting Training Table",
    code: "ILBT0020",
    slug: "flip-top-nesting-training-table",
    category: "Wooden Tables",
    image: img44_1,
    images: [img44_1],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 97,
    material: "Laminate Top & Steel Frame"
  },
  {
    id: 45,
    name: "Sarai Fabric-Strap Outdoor Armchair",
    code: "ILMC0001",
    slug: "sarai-fabric-strap-outdoor-armchair",
    category: "Outdoor Chairs",
    image: img45_2,
    images: [img45_1, img45_2, img45_3, img45_4, img45_5, img45_6, img45_7, img45_8, img45_9, img45_10],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 104,
    material: "Outdoor Fabric & Aluminium"
  },
  {
    id: 46,
    name: "Porto Braided Rope Outdoor Armchair",
    code: "ILMC0002",
    slug: "porto-braided-rope-outdoor-armchair",
    category: "Outdoor Chairs",
    image: img46_1,
    images: [img46_1, img46_2, img46_3, img46_4, img46_5, img46_6, img46_7, img46_8, img46_9, img46_10],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 111,
    material: "Braided Rope & Aluminium"
  },
  {
    id: 47,
    name: "Abra Slatted Steel Outdoor Stacking Chair",
    code: "ILMC0004",
    slug: "abra-slatted-steel-outdoor-stacking-chair",
    category: "Outdoor Chairs",
    image: img47_1,
    images: [img47_1, img47_2, img47_3, img47_4, img47_5, img47_6, img47_7, img47_8, img47_9, img47_10, img47_11, img47_12, img47_13, img47_14, img47_15, img47_16, img47_17, img47_18, img47_19, img47_20, img47_21, img47_22, img47_23, img47_24, img47_25, img47_26, img47_27, img47_28, img47_29, img47_30, img47_31, img47_32, img47_33, img47_34, img47_35, img47_36, img47_37, img47_38, img47_39],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 118,
    material: "Powder-Coated Galvanised Steel"
  },
  {
    id: 48,
    name: "Zechariah Stacking Cord Outdoor Dining Chair",
    code: "ILMC0011",
    slug: "zechariah-stacking-cord-outdoor-dining-chair",
    category: "Outdoor Chairs",
    image: img48_2,
    images: [img48_1, img48_2, img48_3, img48_4, img48_5, img48_6, img48_7, img48_8, img48_9, img48_10, img48_11, img48_12, img48_13, img48_14, img48_15, img48_16, img48_17, img48_18, img48_19, img48_20, img48_21, img48_22, img48_23],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 125,
    material: "UV-Resistant Cord & Steel"
  },
  {
    id: 49,
    name: "Romix Hoop-Frame Slatted Outdoor Chair",
    code: "ILMC0013",
    slug: "romix-hoop-frame-slatted-outdoor-chair",
    category: "Outdoor Chairs",
    image: img49_1,
    images: [img49_1, img49_2, img49_3, img49_4, img49_5, img49_6, img49_7, img49_8, img49_9, img49_10, img49_11, img49_12, img49_13, img49_14, img49_15, img49_16, img49_17, img49_18, img49_19, img49_20, img49_21, img49_22, img49_23, img49_24, img49_25, img49_26, img49_27, img49_28, img49_29, img49_30, img49_31, img49_32, img49_33, img49_34, img49_35, img49_36, img49_37, img49_38, img49_39, img49_40, img49_41, img49_42, img49_43],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 132,
    material: "Slatted Teak & Steel Hoop"
  },
  {
    id: 50,
    name: "Veranda X-Brace Metal Outdoor Loveseat",
    code: "RFOS0101",
    slug: "veranda-x-brace-metal-outdoor-loveseat",
    category: "Outdoor Sofas & Benches",
    image: img50_1,
    images: [img50_1, img50_2, img50_3],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 139,
    material: "Powder-Coated Iron & Cushion"
  },
  {
    id: 51,
    name: "Mira Criss-Cross Rope Outdoor Sofa",
    code: "RFOS0102",
    slug: "mira-criss-cross-rope-outdoor-sofa",
    category: "Outdoor Sofas & Benches",
    image: img51_1,
    images: [img51_1, img51_2, img51_3, img51_4, img51_5, img51_6],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4eff1",
    price: 146,
    material: "Rope Weave & Aluminium Frame"
  },
  {
    id: 52,
    name: "Cabana Stripe Metal Outdoor Sofa",
    code: "RFOS0103",
    slug: "cabana-stripe-metal-outdoor-sofa",
    category: "Outdoor Sofas & Benches",
    image: img52_1,
    images: [img52_1, img52_2, img52_3, img52_4, img52_5],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#eef1ed",
    price: 153,
    material: "Steel Frame & Outdoor Fabric"
  },
  {
    id: 53,
    name: "Sirius Rope Bergère Outdoor Loveseat",
    code: "RFOS0104",
    slug: "sirius-rope-berg-re-outdoor-loveseat",
    category: "Outdoor Sofas & Benches",
    image: img53_1,
    images: [img53_1, img53_2, img53_3, img53_4, img53_5, img53_6, img53_7, img53_8],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f3f3f3",
    price: 160,
    material: "Rope & Powder-Coated Steel"
  },
  {
    id: 54,
    name: "Horizon Rope & Upholstered Low-Profile Loveseat",
    code: "RFOS0105",
    slug: "horizon-rope-upholstered-low-profile-loveseat",
    category: "Outdoor Sofas & Benches",
    image: img54_1,
    images: [img54_1, img54_2, img54_3, img54_4, img54_5, img54_6, img54_7],
    colors: ["#000000","#ffffff","#78350f","#c49a6c"],
    bgColor: "#f4f0eb",
    price: 167,
    material: "Rope, Steel & All-Weather Fabric"
  },
];

export const categoryList = [
  ...new Set(allProducts.map(p => p.category))
].map(catName => ({
  name: catName,
  count: allProducts.filter(p => p.category === catName).length
}));

export const colorList = [
  { name: 'Black', count: 42, hex: 'bg-[#000000]' },
  { name: 'White', count: 28, hex: 'bg-[#ffffff]' },
  { name: 'Brown', count: 35, hex: 'bg-amber-800' },
  { name: 'Beige', count: 16, hex: 'bg-[#e8e2d2]' },
  { name: 'Grey', count: 22, hex: 'bg-gray-400' }
];